apiVersion: v1
kind: Secret
metadata:
    namespace: dwk-project
    name: dwk-project-secret
type: Opaque
data:
    POSTGRES_USER: cG9zdGdyZXM=
    POSTGRES_PASSWORD: ODA4MA==
    POSTGRES_DB: cG9zdGdyZXM=
