apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: dwk-project
  name: job
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: job
            image: sathirak/job:1
          restartPolicy: OnFailure
