apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dwk-project

commonLabels:
  app: dwk-project

resources:
  - persistentvolume.yaml
  - persistentvolumeclaim.yaml
  - ingress.yml
  - cronjob.yml
  - todo/deployment.yml
  - todo/service.yml
  - todo-backend/deployment.yml
  - todo-backend/service.yml
  - postgres/statefulset.yml
  - postgres/service.yml
