
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dwk-project
  name: shared-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi