apiVersion: v1
kind: Service
metadata:
  namespace: dwk-project
  name: todo-svc
spec:
  type: ClusterIP
  selector:
    app: todo 
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3000